config/routes.rb
Rails.application.routes.draw do

  resources :tweets, only: [:index]
  resources :users, only: [:index]

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_nav.erb
<nav>puts some nav stuff here
  <ul>
    <li><%= link_to "Tweets", tweets_path %></li>
    <li><%= link_to "Users", users_path %></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StoneTwitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "application/nav" %>
<%= yield %>

</body>
</html>

app/views/tweets/index.erb
<section>Hello World</section>
<section>
  <ul>
  <% @tweets.each do |tweet| %>
    <li><strong><%=tweet.author %></strong>: <%= tweet.newbody %></li>
  <% end %>
  </ul>
</section>

app/views/users/index.erb
<section>
  <ul>
  <% @users.each do |user| %>
    <li><%= user.first_name %></li>
    <li><%= user.active %></li>
  <% end %>
  </ul>
</section>